### ISSUE TITLE
Too hard to run train.py...

### ISSUE THREAD

**Issue by Tristannnnnnnnn** [UniBwTAS/YOLOPoint#2]
running pip intall -r requirement.txt and it's sooo hard to config the envirenment, can you tell me more details to run this codes to train my model? I followed the README.md but i couldn't run train.py successfully...

**Comment by antopost** [comment]
Hey, glad you're interested in YOLOPoint.
I tried making the project a bit more user-friendly with the last push.
The instructions on getting started should also be a bit clearer in the README.md.
If you're still running into problems, feel free to post the errors/problems here.
