### ISSUE TITLE
what is your visual odometry algorithm?

### ISSUE THREAD

**Issue by jeannotes** [UniBwTAS/YOLOPoint#3]
hi, in section 5.2, you did experiements of Visual Odometry Estimation on KITTI, and I am wondering what is your visual odometry algorithm?can you open source it?
thanks!

**Comment by antopost** [comment]
I used the default algorithm of [pyslam](https://github.com/luigifreda/pyslam).
It uses the cv2.findEssentialMat algorithm with RANSAC.
The code is detailed [here](https://github.com/luigifreda/pyslam/blob/master/visual_odometry.py).

**Comment by jiajiaandWu** [comment]
This Pyslam Use Ground-true to get the VO'scale. That's OK?

**Comment by antopost** [comment]
Yes, comparisons presented in the paper were all done using GT scale.
Since all methods were compared in the same way, I think this is fine.
The algorithms used in pyslam to get the trajectories are all quite basic but sufficient if you just want to compare performance between keypoint algorithms.
