### ISSUE TITLE
Feature point matching problem

### ISSUE THREAD

**Issue by t676290894** [UniBwTAS/YOLOPoint#5]
Thank you for your excellent work，Nearest neighbor matching is generally used in hpatches datasets, and I wonder if the network can match via Superglue or Lightglue

**Comment by antopost** [comment]
I haven't worked with either of the projects, but they should be able to work with YOLOPoint. You would presumably have to retrain the matching network on YOLOPoint features though.

**Comment by t676290894** [comment]
OK . Thank you very much. I will close this question
