### ISSUE TITLE
prolem when using inference.yaml

### ISSUE THREAD

**Issue by gjpblabla** [UniBwTAS/YOLOPoint#6]
Thank you for your outstanding work! When i using $ python src/demo.py --config configs/inference.yaml --weights weights/YOLOPointS.pth.tar --source /path/to/image/folder/or/mp4 to infer my own video, i found the inference.yaml missing, am i wrong?

**Comment by antopost** [comment]
Thanks for raising the issue. You are right, I had either deleted or renamed inference.yaml at some point.
Try using [configs/kitti_inference.yaml](https://github.com/UniBwTAS/YOLOPoint/blob/master/configs/kitti_inference.yaml) or edit it as you need.
Let me know if you run into any problems.
